export const SCREEN_BREAKPOINTS = {
  MOBILE: 768,
  TABLET: 1068,
} as const;

export const ANIMATION_TIMINGS = {
  FADE_IN_DURATION: 0.3,
  FADE_OUT_DURATION: 0.3,
  SCALE_DURATION: 0.5,
  LEVEL_UP_DELAY: 2,
  TUTORIAL_STEP_DELAY: 1.5,
  CAMERA_MOVE_DURATION: 1.5,
  RESIZE_DEBOUNCE: 0.3,
} as const;

