export const SCREEN_BREAKPOINTS = {
  MOBILE: 768,
  TABLET: 968,
} as const;

export const CAMERA_POSITIONS = {
  DESKTOP_Y_OFFSET: -10,
  DESKTOP_Z_OFFSET: -20,
  MOBILE_PORTRAIT_Y_OFFSET: 5,
  MOBILE_PORTRAIT_Z_OFFSET: 10,
} as const;

export const UI_SIZES = {
  MOBILE_PADDING: 10,
  DESKTOP_PADDING: 20,
  MOBILE_ICON_SIZE: 22,
  DESKTOP_ICON_SIZE: 50,
  MOBILE_FONT_SMALL: 12,
  MOBILE_FONT_MEDIUM: 18,
  MOBILE_FONT_LARGE: 28,
  DESKTOP_FONT_SMALL: 14,
  DESKTOP_FONT_MEDIUM: 24,
  DESKTOP_FONT_LARGE: 48,
} as const;

export const ANIMATION_TIMINGS = {
  FADE_IN_DURATION: 0.3,
  FADE_OUT_DURATION: 0.3,
  SCALE_DURATION: 0.5,
  LEVEL_UP_DELAY: 2,
  TUTORIAL_STEP_DELAY: 2.5,
  CAMERA_MOVE_DURATION: 1.5,
  RESIZE_DEBOUNCE: 0.01,
} as const;

export const TUTORIAL = {
  FINGER_SCALE_MOBILE: 0.04,
  FINGER_SCALE_DESKTOP: 0.05,
  SPOTLIGHT_PADDING: 5,
  SPOTLIGHT_BORDER_WIDTH: 4,
  SPOTLIGHT_BORDER_RADIUS: 12,
  POPUP_PADDING_MOBILE: 15,
  POPUP_PADDING_DESKTOP: 20,
  POPUP_BORDER_RADIUS: 12,
  POPUP_BORDER_WIDTH: 3,
  OVERLAY_ALPHA: 0.65,
  FINGER_TAP_OFFSET: 6,
  FINGER_TAP_DURATION: 1.6,
  REPOSITION_DELAY: 0.7,
} as const;

export const LEVELING = {
  PROGRESS_BAR_MOBILE_WIDTH: 150,
  PROGRESS_BAR_DESKTOP_WIDTH: 200,
  PROGRESS_BAR_MOBILE_HEIGHT: 15,
  PROGRESS_BAR_DESKTOP_HEIGHT: 20,
  PANEL_MOBILE_WIDTH: 200,
  PANEL_DESKTOP_WIDTH: 260,
  PANEL_MOBILE_HEIGHT: 75,
  PANEL_DESKTOP_HEIGHT: 100,
  LEVEL_NUMBER_FONT_SIZE: 80,
  LEVEL_UP_TEXT_FONT_SIZE: 36,
  GLOW_RADIUS: 100,
  STAR_COUNT_MOBILE: 12,
  STAR_COUNT_DESKTOP: 20,
  STAR_SIZE_MOBILE: 6,
  STAR_SIZE_DESKTOP: 8,
} as const;

export const GRID_ITEM_PLACEMENT = {
  CIRCLE_SIZE_MOBILE: 22,
  CIRCLE_SIZE_DESKTOP: 50,
  CIRCLE_BORDER_MOBILE: 2,
  CIRCLE_BORDER_DESKTOP: 4,
  QUESTION_MARK_FONT_MOBILE: 20,
  QUESTION_MARK_FONT_DESKTOP: 60,
  QUESTION_MARK_STROKE_MOBILE: 1.5,
  QUESTION_MARK_STROKE_DESKTOP: 4,
  SCALE_HOVER: 1.1,
  SCALE_PULSE_MIN: 1.05,
  ANIMATION_APPEAR_DELAY: 0.2,
  ANIMATION_PULSE_DELAY: 0.8,
  CLAMP_PADDING: 100,
} as const;

export const ITEM_SELECTOR = {
  PANEL_MOBILE_WIDTH: 360,
  PANEL_DESKTOP_WIDTH: 560,
  PANEL_MOBILE_HEIGHT: 140,
  PANEL_DESKTOP_HEIGHT: 180,
  ITEM_SIZE_MOBILE: 70,
  ITEM_SIZE_DESKTOP: 110,
  ITEM_PADDING: 10,
  CLOSE_BUTTON_SIZE: 30,
  CLOSE_BUTTON_FONT_SIZE: 24,
  BORDER_RADIUS: 15,
  BORDER_WIDTH: 4,
} as const;

export const COLORS = {
  GOLD: 0xFFD700,
  GREEN: 0x4CAF50,
  RED: 0xFF0000,
  BLACK: 0x000000,
  WHITE: 0xFFFFFF,
  GRAY: 0x888888,
  DARK_GREEN: 0x2c5f2d,
  BACKGROUND_DARK: 0x333333,
} as const;
