export const SCREEN_BREAKPOINTS = {
  MOBILE: 768,
  TABLET: 1068,
} as const;

export const ANIMATION_TIMINGS = {
  FADE_IN_DURATION: 0.3,
  FADE_OUT_DURATION: 0.3,
  SCALE_DURATION: 0.5,
  LEVEL_UP_DELAY: 2,
  TUTORIAL_STEP_DELAY: 1.5,
  CAMERA_MOVE_DURATION: 1.5,
  RESIZE_DEBOUNCE: 0.3,
} as const;

export const TUTORIAL = {
  FINGER_SCALE_MOBILE: 0.04,
  FINGER_SCALE_DESKTOP: 0.05,
  SPOTLIGHT_PADDING: 5,
  SPOTLIGHT_BORDER_WIDTH: 4,
  SPOTLIGHT_BORDER_RADIUS: 12,
  POPUP_PADDING_MOBILE: 15,
  POPUP_PADDING_DESKTOP: 20,
  POPUP_BORDER_RADIUS: 12,
  POPUP_BORDER_WIDTH: 3,
  OVERLAY_ALPHA: 0.65,
  FINGER_TAP_OFFSET: 6,
  FINGER_TAP_DURATION: 1.6,
  REPOSITION_DELAY: 0.7,
} as const;

export const ITEM_SELECTOR = {
  PANEL_MOBILE_WIDTH: 360,
  PANEL_DESKTOP_WIDTH: 560,
  PANEL_MOBILE_HEIGHT: 140,
  PANEL_DESKTOP_HEIGHT: 180,
  ITEM_SIZE_MOBILE: 70,
  ITEM_SIZE_DESKTOP: 110,
  ITEM_PADDING: 10,
  CLOSE_BUTTON_SIZE: 30,
  CLOSE_BUTTON_FONT_SIZE: 24,
  BORDER_RADIUS: 15,
  BORDER_WIDTH: 4,
} as const;

export const COLORS = {
  GOLD: 0xFFD700,
  GREEN: 0x4CAF50,
  RED: 0xFF0000,
  BLACK: 0x000000,
  WHITE: 0xFFFFFF,
  GRAY: 0x888888,
  DARK_GREEN: 0x2c5f2d,
  BACKGROUND_DARK: 0x333333,
} as const;
